import type { Category } from "../types";

export const areaCategory: Category = {
  id: "area",
  name: "Area",
  group: "common",
  baseUnitId: "square_meter",
  dimension: "L²",
  units: [
    {
      id: "square_meter",
      name: "square meter",
      symbol: "m²",
      aliases: ["square meter", "square meters", "square metre", "sq m", "m2", "m²"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "square_kilometer",
      name: "square kilometer",
      symbol: "km²",
      aliases: ["square kilometer", "square kilometers", "sq km", "km2", "km²"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1000000" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "square_centimeter",
      name: "square centimeter",
      symbol: "cm²",
      aliases: ["square centimeter", "square centimeters", "sq cm", "cm2", "cm²"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.0001" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "square_millimeter",
      name: "square millimeter",
      symbol: "mm²",
      aliases: ["square millimeter", "square millimeters", "sq mm", "mm2", "mm²"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.000001" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "hectare",
      name: "hectare",
      symbol: "ha",
      aliases: ["hectare", "hectares", "ha"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "10000" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "square_inch",
      name: "square inch",
      symbol: "in²",
      aliases: ["square inch", "square inches", "sq in", "in2", "in²"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.00064516" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "square_foot",
      name: "square foot",
      symbol: "ft²",
      aliases: ["square foot", "square feet", "sq ft", "ft2", "ft²"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.09290304" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "square_yard",
      name: "square yard",
      symbol: "yd²",
      aliases: ["square yard", "square yards", "sq yd", "yd2", "yd²"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.83612736" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "acre",
      name: "acre",
      symbol: "ac",
      aliases: ["acre", "acres", "ac"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "4046.8564224" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "square_mile",
      name: "square mile",
      symbol: "mi²",
      aliases: ["square mile", "square miles", "sq mi", "mi2", "mi²"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "2589988.110336" },
      source: "NIST_SP_811",
      exact: true,
    },
  ],
};
