import type { Category } from "../types";

// Base: byte. SI (powers of 10) and IEC binary (powers of 2) units both included.
export const dataStorageCategory: Category = {
  id: "data_storage",
  name: "Data Storage",
  group: "dataTimeAngles",
  baseUnitId: "byte",
  dimension: "data",
  units: [
    {
      id: "bit",
      name: "bit",
      symbol: "bit",
      aliases: ["bit", "bits", "b"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "0.125" },
      source: "APP_DEFINED",
      exact: true,
    },
    {
      id: "byte",
      name: "byte",
      symbol: "B",
      aliases: ["byte", "bytes", "B"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "APP_DEFINED",
      exact: true,
    },
    {
      id: "kilobyte",
      name: "kilobyte",
      symbol: "KB",
      aliases: ["kilobyte", "kilobytes", "KB", "kB"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "1000" },
      source: "APP_DEFINED",
      exact: true,
      notes: "SI kilobyte = 1000 bytes.",
    },
    {
      id: "megabyte",
      name: "megabyte",
      symbol: "MB",
      aliases: ["megabyte", "megabytes", "MB"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "1000000" },
      source: "APP_DEFINED",
      exact: true,
    },
    {
      id: "gigabyte",
      name: "gigabyte",
      symbol: "GB",
      aliases: ["gigabyte", "gigabytes", "GB"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "1000000000" },
      source: "APP_DEFINED",
      exact: true,
    },
    {
      id: "terabyte",
      name: "terabyte",
      symbol: "TB",
      aliases: ["terabyte", "terabytes", "TB"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "1000000000000" },
      source: "APP_DEFINED",
      exact: true,
    },
    {
      id: "kibibyte",
      name: "kibibyte",
      symbol: "KiB",
      aliases: ["kibibyte", "kibibytes", "KiB", "kib"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "1024" },
      source: "APP_DEFINED",
      exact: true,
      notes: "IEC binary kibibyte = 2^10 = 1024 bytes.",
    },
    {
      id: "mebibyte",
      name: "mebibyte",
      symbol: "MiB",
      aliases: ["mebibyte", "mebibytes", "MiB", "mib"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "1048576" },
      source: "APP_DEFINED",
      exact: true,
      notes: "IEC binary mebibyte = 2^20 = 1048576 bytes.",
    },
    {
      id: "gibibyte",
      name: "gibibyte",
      symbol: "GiB",
      aliases: ["gibibyte", "gibibytes", "GiB", "gib"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "1073741824" },
      source: "APP_DEFINED",
      exact: true,
      notes: "IEC binary gibibyte = 2^30 = 1073741824 bytes.",
    },
    {
      id: "tebibyte",
      name: "tebibyte",
      symbol: "TiB",
      aliases: ["tebibyte", "tebibytes", "TiB", "tib"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "1099511627776" },
      source: "APP_DEFINED",
      exact: true,
      notes: "IEC binary tebibyte = 2^40 = 1099511627776 bytes.",
    },
  ],
};
