import type { Category } from "../types";

export const densityCategory: Category = {
  id: "density",
  name: "Density",
  group: "mechanical",
  baseUnitId: "kilogram_per_cubic_meter",
  dimension: "M/L³",
  units: [
    {
      id: "kilogram_per_cubic_meter",
      name: "kilogram per cubic meter",
      symbol: "kg/m³",
      aliases: ["kg/m3", "kg/m³", "kilogram per cubic meter"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "gram_per_cubic_centimeter",
      name: "gram per cubic centimeter",
      symbol: "g/cm³",
      aliases: ["g/cm3", "g/cm³", "gram per cubic centimeter", "g/cc"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "1000" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "gram_per_milliliter",
      name: "gram per milliliter",
      symbol: "g/mL",
      aliases: ["g/ml", "g/mL", "gram per milliliter"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "1000" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "kilogram_per_liter",
      name: "kilogram per liter",
      symbol: "kg/L",
      aliases: ["kg/L", "kg/l", "kilogram per liter"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "1000" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "pound_per_cubic_foot",
      name: "pound per cubic foot",
      symbol: "lb/ft³",
      aliases: ["lb/ft3", "lb/ft³", "lbm/ft3", "pound per cubic foot", "pcf"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "16.018463373960142" },
      source: "NIST_SP_811",
    },
    {
      id: "pound_per_cubic_inch",
      name: "pound per cubic inch",
      symbol: "lb/in³",
      aliases: ["lb/in3", "lb/in³", "lbm/in3", "pound per cubic inch"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "27679.904710191" },
      source: "NIST_SP_811",
    },
  ],
};
