import type { Category } from "../types";

// Base: joule.
// Btu definition used: International Table Btu = 1055.05585262 J (NIST SP 811)
// Calorie definition used: International Table calorie = 4.1868 J (NIST SP 811)
export const energyCategory: Category = {
  id: "energy",
  name: "Energy",
  group: "mechanical",
  baseUnitId: "joule",
  dimension: "M·L²/T²",
  units: [
    {
      id: "joule",
      name: "joule",
      symbol: "J",
      aliases: ["joule", "joules", "J"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "kilojoule",
      name: "kilojoule",
      symbol: "kJ",
      aliases: ["kilojoule", "kilojoules", "kJ"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1000" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "megajoule",
      name: "megajoule",
      symbol: "MJ",
      aliases: ["megajoule", "megajoules", "MJ"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1000000" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "watt_hour",
      name: "watt hour",
      symbol: "Wh",
      aliases: ["watt hour", "watt hours", "wh", "Wh"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "3600" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "kilowatt_hour",
      name: "kilowatt hour",
      symbol: "kWh",
      aliases: ["kilowatt hour", "kilowatt hours", "kwh", "kWh"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "3600000" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "calorie_it",
      name: "calorie (IT)",
      symbol: "cal",
      aliases: ["calorie", "calories", "cal", "calorie it"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "4.1868" },
      source: "NIST_SP_811",
      exact: true,
      notes: "International Table calorie = 4.1868 J exactly.",
    },
    {
      id: "kilocalorie_it",
      name: "kilocalorie (IT)",
      symbol: "kcal",
      aliases: ["kilocalorie", "kilocalories", "kcal", "food calorie", "Cal"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "4186.8" },
      source: "NIST_SP_811",
      exact: true,
      notes: "IT kilocalorie = 4186.8 J. Used in food/nutrition.",
    },
    {
      id: "btu_it",
      name: "Btu (IT)",
      symbol: "Btu",
      aliases: ["btu", "Btu", "british thermal unit", "btu it"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "1055.05585262" },
      source: "NIST_SP_811",
      notes: "International Table Btu = 1055.05585262 J (NIST SP 811 Appendix B).",
    },
    {
      id: "foot_pound_force",
      name: "foot-pound force",
      symbol: "ft·lbf",
      aliases: ["ft-lbf", "ft·lbf", "ft-lb", "foot pound", "foot-pound force"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "1.3558179483314004" },
      source: "NIST_SP_811",
    },
    {
      id: "electronvolt",
      name: "electronvolt",
      symbol: "eV",
      aliases: ["electronvolt", "electron volt", "eV"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "1.602176634e-19" },
      source: "CODATA",
      exact: true,
    },
  ],
};
