import type { Category } from "../types";

// Volumetric flow. Base: cubic meter per second.
export const flowCategory: Category = {
  id: "flow",
  name: "Volumetric Flow",
  group: "fluids",
  baseUnitId: "cubic_meter_per_second",
  dimension: "L³/T",
  units: [
    {
      id: "cubic_meter_per_second",
      name: "cubic meter per second",
      symbol: "m³/s",
      aliases: ["m3/s", "m³/s", "cubic meter per second", "cms"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "cubic_meter_per_hour",
      name: "cubic meter per hour",
      symbol: "m³/h",
      aliases: ["m3/h", "m³/h", "cubic meter per hour"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.00027777777777777777777777778" },
      source: "BIPM_SI",
    },
    {
      id: "liter_per_second",
      name: "liter per second",
      symbol: "L/s",
      aliases: ["L/s", "l/s", "liter per second"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "0.001" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "liter_per_minute",
      name: "liter per minute",
      symbol: "L/min",
      aliases: ["L/min", "l/min", "lpm", "liter per minute"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "0.000016666666666666666666666667" },
      source: "NIST_SP_811",
    },
    {
      id: "us_gallon_per_minute",
      name: "US gallon per minute",
      symbol: "US gpm",
      aliases: ["gpm", "us gpm", "gallon per minute", "US gpm", "usgpm"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.000063090196666666666666666667" },
      source: "NIST_SP_811",
      notes: "US gallon per minute = 3.785411784 L / 60 s.",
    },
    {
      id: "imperial_gallon_per_minute",
      name: "Imperial gallon per minute",
      symbol: "imp gpm",
      aliases: ["imp gpm", "imperial gpm", "uk gpm"],
      system: "Imperial",
      kind: "linear",
      toBase: { multiplier: "0.000075768166666666666666666667" },
      source: "NIST_SP_811",
    },
    {
      id: "cubic_foot_per_second",
      name: "cubic foot per second",
      symbol: "ft³/s",
      aliases: ["ft3/s", "ft³/s", "cfs", "cubic foot per second"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.028316846592" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "cubic_foot_per_minute",
      name: "cubic foot per minute",
      symbol: "ft³/min",
      aliases: ["ft3/min", "ft³/min", "cfm", "cubic foot per minute"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.00047194744319999999999" },
      source: "NIST_SP_811",
    },
    {
      id: "barrel_per_day",
      name: "barrel per day (oil)",
      symbol: "bbl/d",
      aliases: ["bbl/d", "barrel per day", "bpd"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.0000018401307291666667" },
      source: "APP_DEFINED",
      notes: "US petroleum barrel = 42 US gallons.",
    },
  ],
};

// Mass flow. Base: kilogram per second.
export const massFlowCategory: Category = {
  id: "mass_flow",
  name: "Mass Flow",
  group: "fluids",
  baseUnitId: "kilogram_per_second",
  dimension: "M/T",
  units: [
    {
      id: "kilogram_per_second",
      name: "kilogram per second",
      symbol: "kg/s",
      aliases: ["kg/s", "kilogram per second"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "kilogram_per_hour",
      name: "kilogram per hour",
      symbol: "kg/h",
      aliases: ["kg/h", "kilogram per hour"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.00027777777777777778" },
      source: "BIPM_SI",
    },
    {
      id: "gram_per_second",
      name: "gram per second",
      symbol: "g/s",
      aliases: ["g/s", "gram per second"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.001" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "pound_per_second",
      name: "pound per second",
      symbol: "lb/s",
      aliases: ["lb/s", "lbm/s", "pound per second"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.45359237" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "pound_per_hour",
      name: "pound per hour",
      symbol: "lb/h",
      aliases: ["lb/h", "lbm/h", "pound per hour"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.00012599788055555556" },
      source: "NIST_SP_811",
    },
  ],
};
