import type { Category } from "../types";

// Force only — mass (kg, lbm, etc.) is in mass.ts
// Base: newton. Source: NIST SP 811
export const forceCategory: Category = {
  id: "force",
  name: "Force",
  group: "mechanical",
  baseUnitId: "newton",
  dimension: "M·L/T²",
  units: [
    {
      id: "newton",
      name: "newton",
      symbol: "N",
      aliases: ["newton", "newtons", "N"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "kilonewton",
      name: "kilonewton",
      symbol: "kN",
      aliases: ["kilonewton", "kilonewtons", "kN"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1000" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "pound_force",
      name: "pound-force",
      symbol: "lbf",
      aliases: ["pound force", "pound-force", "lbf", "lb-f", "lb force"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "4.4482216152605" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "kip",
      name: "kip",
      symbol: "kip",
      aliases: ["kip", "kips", "kilopound", "klbf"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "4448.2216152605" },
      source: "NIST_SP_811",
      exact: true,
      notes: "1 kip = 1000 lbf.",
    },
    {
      id: "kilogram_force",
      name: "kilogram-force",
      symbol: "kgf",
      aliases: ["kilogram force", "kilogram-force", "kgf", "kg-f", "kilopond"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "9.80665" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "dyne",
      name: "dyne",
      symbol: "dyn",
      aliases: ["dyne", "dynes", "dyn"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "0.00001" },
      source: "NIST_SP_811",
      exact: true,
    },
  ],
};
