import type { Category } from "../types";

export const lengthCategory: Category = {
  id: "length",
  name: "Length",
  group: "common",
  baseUnitId: "meter",
  dimension: "L",
  units: [
    {
      id: "meter",
      name: "meter",
      symbol: "m",
      aliases: ["meter", "meters", "metre", "metres", "m"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "kilometer",
      name: "kilometer",
      symbol: "km",
      aliases: ["kilometer", "kilometers", "kilometre", "kilometres", "km"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1000" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "centimeter",
      name: "centimeter",
      symbol: "cm",
      aliases: ["centimeter", "centimeters", "centimetre", "centimetres", "cm"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.01" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "millimeter",
      name: "millimeter",
      symbol: "mm",
      aliases: ["millimeter", "millimeters", "millimetre", "millimetres", "mm"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.001" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "micrometer",
      name: "micrometer",
      symbol: "µm",
      aliases: ["micrometer", "micrometers", "micrometre", "micrometres", "um", "µm", "micron", "microns"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.000001" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "nanometer",
      name: "nanometer",
      symbol: "nm",
      aliases: ["nanometer", "nanometers", "nanometre", "nanometres", "nm"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.000000001" },
      source: "BIPM_SI",
      exact: true,
      notes: "nm is ambiguous: could be nanometer (length) or newton-meter (torque). Context is length here.",
    },
    {
      id: "inch",
      name: "inch",
      symbol: "in",
      aliases: ["inch", "inches", "in", '"'],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.0254" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "foot",
      name: "foot",
      symbol: "ft",
      aliases: ["foot", "feet", "ft", "'"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.3048" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "yard",
      name: "yard",
      symbol: "yd",
      aliases: ["yard", "yards", "yd"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.9144" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "mile",
      name: "mile",
      symbol: "mi",
      aliases: ["mile", "miles", "mi"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "1609.344" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "nautical_mile",
      name: "nautical mile",
      symbol: "nmi",
      aliases: ["nautical mile", "nautical miles", "nmi", "nm nautical"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "1852" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "mil",
      name: "mil (thou)",
      symbol: "mil",
      aliases: ["mil", "mils", "thou", "thousandth"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.0000254" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "us_survey_foot",
      name: "US survey foot",
      symbol: "ft (survey)",
      aliases: ["us survey foot", "survey foot", "survey feet"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.3048006096012192" },
      source: "NIST_SP_811",
      legacy: true,
      notes: "US survey foot is legacy. Use international foot (0.3048 m exactly) for new work. Avoid in new work per NIST guidance effective 2023.",
    },
  ],
};
