import type { Category } from "../types";

// Mass only — force (lbf, N, etc.) is in force.ts
// Source: NIST SP 811
export const massCategory: Category = {
  id: "mass",
  name: "Mass",
  group: "common",
  baseUnitId: "kilogram",
  dimension: "M",
  units: [
    {
      id: "kilogram",
      name: "kilogram",
      symbol: "kg",
      aliases: ["kilogram", "kilograms", "kg"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "gram",
      name: "gram",
      symbol: "g",
      aliases: ["gram", "grams", "g"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.001" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "milligram",
      name: "milligram",
      symbol: "mg",
      aliases: ["milligram", "milligrams", "mg"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.000001" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "metric_tonne",
      name: "metric tonne",
      symbol: "t",
      aliases: ["metric tonne", "metric tonnes", "tonne", "tonnes", "metric ton", "t"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "1000" },
      source: "NIST_SP_811",
      exact: true,
      notes: "tonne = 1000 kg. Not to be confused with short ton (2000 lbm) or long ton (2240 lbm).",
    },
    {
      id: "pound_mass",
      name: "pound (mass)",
      symbol: "lbm",
      aliases: ["pound", "pounds", "lb", "lbm", "pound mass"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.45359237" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "ounce_mass",
      name: "ounce (mass)",
      symbol: "oz",
      aliases: ["ounce", "ounces", "oz", "ounce mass", "oz mass"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.028349523125" },
      source: "NIST_SP_811",
      exact: true,
      notes: "oz is ambiguous: oz mass (this) vs fl oz (volume). This is mass ounce.",
    },
    {
      id: "slug",
      name: "slug",
      symbol: "slug",
      aliases: ["slug", "slugs"],
      system: "Engineering",
      kind: "linear",
      toBase: { multiplier: "14.593902937206" },
      source: "NIST_SP_811",
      notes: "Engineering unit. 1 slug = 1 lbf·s²/ft.",
    },
    {
      id: "short_ton",
      name: "short ton",
      symbol: "ton",
      aliases: ["short ton", "short tons", "us ton", "ton"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "907.18474" },
      source: "NIST_SP_811",
      exact: true,
      notes: "US short ton = 2000 lbm. Distinct from long ton (2240 lbm) and metric tonne (1000 kg).",
    },
    {
      id: "long_ton",
      name: "long ton",
      symbol: "LT",
      aliases: ["long ton", "long tons", "imperial ton", "uk ton", "LT"],
      system: "Imperial",
      kind: "linear",
      toBase: { multiplier: "1016.0469088" },
      source: "NIST_SP_811",
      exact: true,
      notes: "Imperial long ton = 2240 lbm. Distinct from US short ton (2000 lbm) and metric tonne (1000 kg).",
    },
  ],
};
