import type { Category } from "../types";

// Base: watt.
// Mechanical horsepower: 550 ft·lbf/s = 745.69987158227022 W (NIST SP 811)
// Metric horsepower: 75 kgf·m/s = 735.49875 W
// Btu/h uses International Table Btu = 1055.05585262 J / 3600 s
export const powerCategory: Category = {
  id: "power",
  name: "Power",
  group: "mechanical",
  baseUnitId: "watt",
  dimension: "M·L²/T³",
  units: [
    {
      id: "watt",
      name: "watt",
      symbol: "W",
      aliases: ["watt", "watts", "W"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "kilowatt",
      name: "kilowatt",
      symbol: "kW",
      aliases: ["kilowatt", "kilowatts", "kW"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1000" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "megawatt",
      name: "megawatt",
      symbol: "MW",
      aliases: ["megawatt", "megawatts", "MW"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1000000" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "horsepower_mech",
      name: "horsepower (mechanical)",
      symbol: "hp",
      aliases: ["horsepower", "hp", "mechanical horsepower", "hp mech"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "745.69987158227022" },
      source: "NIST_SP_811",
      notes: "Mechanical horsepower = 550 ft·lbf/s.",
    },
    {
      id: "horsepower_metric",
      name: "horsepower (metric)",
      symbol: "PS",
      aliases: ["metric horsepower", "ps", "PS", "cv", "pferdestärke"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "735.49875" },
      source: "NIST_SP_811",
      exact: true,
      notes: "Metric horsepower = 75 kgf·m/s.",
    },
    {
      id: "btu_per_hour",
      name: "Btu per hour",
      symbol: "Btu/h",
      aliases: ["btu/h", "btu per hour", "Btu/h", "btuh"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.29307107017222" },
      source: "NIST_SP_811",
      notes: "Uses International Table Btu (1055.05585262 J) / 3600 s.",
    },
    {
      id: "foot_pound_per_second",
      name: "foot-pound force per second",
      symbol: "ft·lbf/s",
      aliases: ["ft-lbf/s", "ft·lbf/s", "ft-lb/s", "foot pound per second"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "1.3558179483314004" },
      source: "NIST_SP_811",
    },
  ],
};
