import type { Category } from "../types";

// Base: pascal. Source: NIST SP 811
export const pressureCategory: Category = {
  id: "pressure",
  name: "Pressure",
  group: "mechanical",
  baseUnitId: "pascal",
  dimension: "M/(L·T²)",
  units: [
    {
      id: "pascal",
      name: "pascal",
      symbol: "Pa",
      aliases: ["pascal", "pascals", "Pa"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "kilopascal",
      name: "kilopascal",
      symbol: "kPa",
      aliases: ["kilopascal", "kilopascals", "kPa"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1000" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "megapascal",
      name: "megapascal",
      symbol: "MPa",
      aliases: ["megapascal", "megapascals", "MPa"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1000000" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "gigapascal",
      name: "gigapascal",
      symbol: "GPa",
      aliases: ["gigapascal", "gigapascals", "GPa"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1000000000" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "bar",
      name: "bar",
      symbol: "bar",
      aliases: ["bar", "bars"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "100000" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "millibar",
      name: "millibar",
      symbol: "mbar",
      aliases: ["millibar", "millibars", "mbar"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "100" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "atmosphere",
      name: "atmosphere",
      symbol: "atm",
      aliases: ["atmosphere", "atmospheres", "atm", "standard atmosphere"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "101325" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "psi",
      name: "pound per square inch",
      symbol: "psi",
      aliases: ["psi", "lb/in2", "lbf/in2", "pound per square inch"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "6894.757293168361" },
      source: "NIST_SP_811",
    },
    {
      id: "ksi",
      name: "kilo-pound per square inch",
      symbol: "ksi",
      aliases: ["ksi", "klbf/in2", "kip per square inch"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "6894757.293168361" },
      source: "NIST_SP_811",
    },
    {
      id: "torr",
      name: "torr",
      symbol: "Torr",
      aliases: ["torr", "Torr"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "133.32236842105263157894736842" },
      source: "NIST_SP_811",
      notes: "1 Torr = 101325/760 Pa.",
    },
    {
      id: "mmhg",
      name: "millimeter of mercury",
      symbol: "mmHg",
      aliases: ["mmhg", "mmHg", "mm hg", "mm mercury"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "133.32236842105263157894736842" },
      source: "NIST_SP_811",
      notes: "mmHg ≈ Torr for medical/atmospheric purposes.",
    },
    {
      id: "inhg",
      name: "inch of mercury",
      symbol: "inHg",
      aliases: ["inhg", "inHg", "in hg", "in mercury"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "3386.389" },
      source: "NIST_SP_811",
    },
    {
      id: "inh2o",
      name: "inch of water",
      symbol: "inH₂O",
      aliases: ["inh2o", "inH2O", "in h2o", "in water", "inch water column"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "249.08890577507" },
      source: "NIST_SP_811",
      notes: "Based on water at 4°C (maximum density).",
    },
  ],
};
