import type { Category } from "../types";

export const speedCategory: Category = {
  id: "speed",
  name: "Speed",
  group: "common",
  baseUnitId: "meter_per_second",
  dimension: "L/T",
  units: [
    {
      id: "meter_per_second",
      name: "meter per second",
      symbol: "m/s",
      aliases: ["meter per second", "meters per second", "m/s", "mps"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "kilometer_per_hour",
      name: "kilometer per hour",
      symbol: "km/h",
      aliases: ["kilometer per hour", "kilometres per hour", "km/h", "kph", "kmh"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "0.2777777777777777777777777778" },
      source: "NIST_SP_811",
    },
    {
      id: "mile_per_hour",
      name: "mile per hour",
      symbol: "mph",
      aliases: ["mile per hour", "miles per hour", "mph"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.44704" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "foot_per_second",
      name: "foot per second",
      symbol: "ft/s",
      aliases: ["foot per second", "feet per second", "ft/s", "fps"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.3048" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "knot",
      name: "knot",
      symbol: "kn",
      aliases: ["knot", "knots", "kn", "kt"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "0.5144444444444444444444444444" },
      source: "NIST_SP_811",
      notes: "1 knot = 1 nautical mile per hour = 1852/3600 m/s.",
    },
  ],
};
