import type { Category } from "../types";

export const timeCategory: Category = {
  id: "time",
  name: "Time",
  group: "dataTimeAngles",
  baseUnitId: "second",
  dimension: "T",
  units: [
    {
      id: "second",
      name: "second",
      symbol: "s",
      aliases: ["second", "seconds", "sec", "s"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "millisecond",
      name: "millisecond",
      symbol: "ms",
      aliases: ["millisecond", "milliseconds", "ms"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.001" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "microsecond",
      name: "microsecond",
      symbol: "µs",
      aliases: ["microsecond", "microseconds", "us", "µs"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.000001" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "minute",
      name: "minute",
      symbol: "min",
      aliases: ["minute", "minutes", "min"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "60" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "hour",
      name: "hour",
      symbol: "h",
      aliases: ["hour", "hours", "hr", "h"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "3600" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "day",
      name: "day",
      symbol: "d",
      aliases: ["day", "days", "d"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "86400" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "week",
      name: "week",
      symbol: "wk",
      aliases: ["week", "weeks", "wk"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "604800" },
      source: "APP_DEFINED",
      exact: true,
    },
    {
      id: "julian_year",
      name: "year (Julian)",
      symbol: "yr",
      aliases: ["year", "years", "yr", "julian year"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "31557600" },
      source: "APP_DEFINED",
      notes: "Julian year = 365.25 days = 31557600 s. Commonly used for approximation.",
    },
  ],
};
