import type { Category } from "../types";

// Base: newton-meter. Source: NIST SP 811
// nm is ambiguous (nanometer / newton-meter); this category uses N-m consistently.
export const torqueCategory: Category = {
  id: "torque",
  name: "Torque",
  group: "mechanical",
  baseUnitId: "newton_meter",
  dimension: "M·L²/T²",
  units: [
    {
      id: "newton_meter",
      name: "newton meter",
      symbol: "N·m",
      aliases: ["newton meter", "newton meters", "n-m", "n·m", "nm torque", "N·m", "Nm"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "newton_millimeter",
      name: "newton millimeter",
      symbol: "N·mm",
      aliases: ["newton millimeter", "newton millimeters", "n-mm", "n·mm", "N·mm"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.001" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "kilonewton_meter",
      name: "kilonewton meter",
      symbol: "kN·m",
      aliases: ["kilonewton meter", "kilonewton meters", "kn-m", "kN·m"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1000" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "pound_force_foot",
      name: "pound-force foot",
      symbol: "lbf·ft",
      aliases: ["lbf-ft", "lbf·ft", "lb-ft", "ft-lb", "ft-lbf", "pound-force foot", "pound force foot"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "1.3558179483314004" },
      source: "NIST_SP_811",
    },
    {
      id: "pound_force_inch",
      name: "pound-force inch",
      symbol: "lbf·in",
      aliases: ["lbf-in", "lbf·in", "lb-in", "in-lb", "in-lbf", "pound-force inch", "pound force inch"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.11298482902762504" },
      source: "NIST_SP_811",
    },
    {
      id: "ounce_force_inch",
      name: "ounce-force inch",
      symbol: "ozf·in",
      aliases: ["ozf-in", "ozf·in", "oz-in", "in-oz", "ounce-force inch"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.0070615518142265650" },
      source: "NIST_SP_811",
    },
    {
      id: "kilogram_force_meter",
      name: "kilogram-force meter",
      symbol: "kgf·m",
      aliases: ["kgf-m", "kgf·m", "kg-m", "kilogram force meter"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "9.80665" },
      source: "NIST_SP_811",
      exact: true,
    },
  ],
};
