import type { Category } from "../types";

// Dynamic viscosity. Base: pascal-second (Pa·s).
export const dynamicViscosityCategory: Category = {
  id: "dynamic_viscosity",
  name: "Dynamic Viscosity",
  group: "fluids",
  baseUnitId: "pascal_second",
  dimension: "M/(L·T)",
  units: [
    {
      id: "pascal_second",
      name: "pascal second",
      symbol: "Pa·s",
      aliases: ["Pa·s", "Pa-s", "pascal second", "pascal-second"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "millipascal_second",
      name: "millipascal second",
      symbol: "mPa·s",
      aliases: ["mPa·s", "mPa-s", "millipascal second"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.001" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "poise",
      name: "poise",
      symbol: "P",
      aliases: ["poise", "P"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "0.1" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "centipoise",
      name: "centipoise",
      symbol: "cP",
      aliases: ["centipoise", "cP"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "0.001" },
      source: "NIST_SP_811",
      exact: true,
      notes: "1 cP = 1 mPa·s.",
    },
    {
      id: "lb_per_ft_s",
      name: "pound per foot second",
      symbol: "lb/(ft·s)",
      aliases: ["lb/(ft·s)", "lbm/(ft·s)", "lb/ft-s"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "1.4881639435695542" },
      source: "NIST_SP_811",
    },
  ],
};

// Kinematic viscosity. Base: square meter per second (m²/s).
export const kinematicViscosityCategory: Category = {
  id: "kinematic_viscosity",
  name: "Kinematic Viscosity",
  group: "fluids",
  baseUnitId: "square_meter_per_second",
  dimension: "L²/T",
  units: [
    {
      id: "square_meter_per_second",
      name: "square meter per second",
      symbol: "m²/s",
      aliases: ["m2/s", "m²/s", "square meter per second"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "square_millimeter_per_second",
      name: "square millimeter per second",
      symbol: "mm²/s",
      aliases: ["mm2/s", "mm²/s", "square millimeter per second"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.000000001" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "stokes",
      name: "stokes",
      symbol: "St",
      aliases: ["stokes", "St"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "0.0001" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "centistokes",
      name: "centistokes",
      symbol: "cSt",
      aliases: ["centistokes", "cSt"],
      system: "Other",
      kind: "linear",
      toBase: { multiplier: "0.000000001" },
      source: "NIST_SP_811",
      exact: true,
      notes: "1 cSt = 1 mm²/s.",
    },
    {
      id: "square_foot_per_second",
      name: "square foot per second",
      symbol: "ft²/s",
      aliases: ["ft2/s", "ft²/s", "square foot per second"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.09290304" },
      source: "NIST_SP_811",
      exact: true,
    },
  ],
};
