import type { Category } from "../types";

// US and Imperial volume units are kept separate where they differ.
// Source: NIST SP 811 / NIST Handbook 44
export const volumeCategory: Category = {
  id: "volume",
  name: "Volume",
  group: "common",
  baseUnitId: "cubic_meter",
  dimension: "L³",
  units: [
    {
      id: "cubic_meter",
      name: "cubic meter",
      symbol: "m³",
      aliases: ["cubic meter", "cubic meters", "cubic metre", "m3", "m³"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "1" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "liter",
      name: "liter",
      symbol: "L",
      aliases: ["liter", "liters", "litre", "litres", "l", "L"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "0.001" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "milliliter",
      name: "milliliter",
      symbol: "mL",
      aliases: ["milliliter", "milliliters", "millilitre", "ml", "mL", "cc"],
      system: "Metric",
      kind: "linear",
      toBase: { multiplier: "0.000001" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "cubic_centimeter",
      name: "cubic centimeter",
      symbol: "cm³",
      aliases: ["cubic centimeter", "cubic centimeters", "cm3", "cm³", "cubic cm"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.000001" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "cubic_millimeter",
      name: "cubic millimeter",
      symbol: "mm³",
      aliases: ["cubic millimeter", "cubic millimeters", "mm3", "mm³"],
      system: "SI",
      kind: "linear",
      toBase: { multiplier: "0.000000001" },
      source: "BIPM_SI",
      exact: true,
    },
    {
      id: "cubic_inch",
      name: "cubic inch",
      symbol: "in³",
      aliases: ["cubic inch", "cubic inches", "in3", "in³", "cu in"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.000016387064" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "cubic_foot",
      name: "cubic foot",
      symbol: "ft³",
      aliases: ["cubic foot", "cubic feet", "ft3", "ft³", "cu ft", "cfm"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.028316846592" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "cubic_yard",
      name: "cubic yard",
      symbol: "yd³",
      aliases: ["cubic yard", "cubic yards", "yd3", "yd³", "cu yd"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.764554857984" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "us_gallon",
      name: "US gallon",
      symbol: "US gal",
      aliases: ["us gallon", "us gallons", "gallon", "gallons", "gal", "usgal"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.003785411784" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "imperial_gallon",
      name: "Imperial gallon",
      symbol: "imp gal",
      aliases: ["imperial gallon", "imperial gallons", "imp gal", "uk gallon", "ukgal"],
      system: "Imperial",
      kind: "linear",
      toBase: { multiplier: "0.00454609" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "us_quart",
      name: "US quart",
      symbol: "US qt",
      aliases: ["us quart", "us quarts", "quart", "quarts", "qt"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.000946352946" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "imperial_quart",
      name: "Imperial quart",
      symbol: "imp qt",
      aliases: ["imperial quart", "imperial quarts", "imp qt", "uk quart"],
      system: "Imperial",
      kind: "linear",
      toBase: { multiplier: "0.0011365225" },
      source: "NIST_SP_811",
    },
    {
      id: "us_pint",
      name: "US pint",
      symbol: "US pt",
      aliases: ["us pint", "us pints", "pint", "pints", "pt"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.000473176473" },
      source: "NIST_SP_811",
      exact: true,
    },
    {
      id: "imperial_pint",
      name: "Imperial pint",
      symbol: "imp pt",
      aliases: ["imperial pint", "imperial pints", "imp pt", "uk pint"],
      system: "Imperial",
      kind: "linear",
      toBase: { multiplier: "0.00056826125" },
      source: "NIST_SP_811",
    },
    {
      id: "us_fluid_ounce",
      name: "US fluid ounce",
      symbol: "US fl oz",
      aliases: ["us fluid ounce", "us fl oz", "fluid ounce", "fl oz", "floz"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.0000295735295625" },
      source: "NIST_SP_811",
      exact: true,
      notes: "oz is ambiguous: fl oz (volume) vs oz mass. This is fluid ounce.",
    },
    {
      id: "imperial_fluid_ounce",
      name: "Imperial fluid ounce",
      symbol: "imp fl oz",
      aliases: ["imperial fluid ounce", "imp fl oz", "uk fluid ounce", "uk fl oz"],
      system: "Imperial",
      kind: "linear",
      toBase: { multiplier: "0.0000284130625" },
      source: "NIST_SP_811",
    },
    {
      id: "barrel_oil",
      name: "barrel (oil)",
      symbol: "bbl",
      aliases: ["barrel", "barrels", "bbl", "oil barrel"],
      system: "USCustomary",
      kind: "linear",
      toBase: { multiplier: "0.158987294928" },
      source: "APP_DEFINED",
      notes: "US petroleum barrel = 42 US gallons.",
    },
  ],
};
